version: '3.8'

services:
  api:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=restdb
    depends_on:
      - mongo
    networks:
      - flask-mongo-net

  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    networks:
      - flask-mongo-net

networks:
  flask-mongo-net:
    driver: bridge

volumes:
  mongo_data:
