version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "5000:5000"  # Expone la app en el puerto 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017  # MongoDB en el servicio "mongo"
      - MONGO_DB=restdb
    depends_on:
      - mongo  # Espera a que el servicio "mongo" esté listo
  mongo:
    image: mongo:6.0  # Usa la imagen oficial de MongoDB
    container_name: mongo
    ports:
      - "27017:27017"  # Expone MongoDB en el puerto 27017
    volumes:
      - mongo_data:/data/db  # Persistencia de datos

volumes:
  mongo_data: